CREATE DATABASE IF NOT EXISTS GESTION_DES_COURS DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE GESTION_DES_COURS;

CREATE TABLE IF NOT EXISTS T_MATIERE (
    ID_MATIERE INT AUTO_INCREMENT PRIMARY KEY,
    NOM_MATIERE VARCHAR(100) NOT NULL,
    NIVEAU VARCHAR(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS T_CHAPITRE (
    ID_CHAPITRE INT AUTO_INCREMENT PRIMARY KEY,
    NOM_CHAPITRE VARCHAR(150) NOT NULL,
    DETAIL_CHAPITRE TEXT,
    CHEMIN_FICHIER VARCHAR(255),
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
